---
abstract: 'Track unique keys in ElasticSearch'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  ElasticSearch: 0.55
  ElasticSearch::TestServer: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearchX-UniqueKey
requires:
  Carp: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/clintongormley/ElasticSearchX-UniqueKey/issues
  repository: git://github.com/clintongormley/ElasticSearchX-UniqueKey.git
version: 0.03
